-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 08:39:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema roofing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema roofing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `roofing` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `roofing` ;

-- -----------------------------------------------------
-- Table `roofing`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roofing`.`Customer` (
  `claim_number` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `acceptance` VARCHAR(45) NOT NULL,
  `customer_survey` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`claim_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roofing`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roofing`.`Invoice` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATETIME NOT NULL,
  `insurance_company` VARCHAR(45) NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `estimate` DECIMAL(10,2) NOT NULL,
  `card_type` VARCHAR(45) NOT NULL,
  `card_number` VARCHAR(45) NOT NULL,
  `card_expiration` VARCHAR(45) NOT NULL,
  `card_cvv` VARCHAR(45) NOT NULL,
  `line_description` VARCHAR(255) NOT NULL,
  `material_amount` VARCHAR(45) NOT NULL,
  `Customer_claim_number` INT NOT NULL,
  `Sales Representative_sales_rep_id` INT NOT NULL,
  PRIMARY KEY (`invoice_id`),
  INDEX `fk_Invoice_Customer1_idx` (`Customer_claim_number` ASC) VISIBLE,
  INDEX `fk_Invoice_Sales Representative1_idx` (`Sales Representative_sales_rep_id` ASC) VISIBLE,
  CONSTRAINT `fk_Invoice_Customer1`
    FOREIGN KEY (`Customer_claim_number`)
    REFERENCES `roofing`.`Customer` (`claim_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_Sales Representative1`
    FOREIGN KEY (`Sales Representative_sales_rep_id`)
    REFERENCES `roofing`.`Sales Representative` (`sales_rep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roofing`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roofing`.`Payment` (
  `payment_id` INT NOT NULL,
  `num_of_payments` INT NOT NULL,
  `amount_paid` INT NOT NULL,
  `balance` INT NOT NULL,
  `Invoice_invoice_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_Payment_Invoice1_idx` (`Invoice_invoice_id` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Invoice1`
    FOREIGN KEY (`Invoice_invoice_id`)
    REFERENCES `roofing`.`Invoice` (`invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roofing`.`Roof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roofing`.`Roof` (
  `roof_id` INT NOT NULL,
  `square_footage` DECIMAL(10,2) NOT NULL,
  `num_of_vents` INT NOT NULL,
  `age_of_roof` INT NOT NULL,
  `roof_pitch` VARCHAR(45) NOT NULL,
  `Customer_claim_number` INT NOT NULL,
  `Sales Representative_sales_rep_id` INT NOT NULL,
  PRIMARY KEY (`roof_id`),
  INDEX `fk_Roof_Customer_idx` (`Customer_claim_number` ASC) VISIBLE,
  INDEX `fk_Roof_Sales Representative1_idx` (`Sales Representative_sales_rep_id` ASC) VISIBLE,
  CONSTRAINT `fk_Roof_Customer`
    FOREIGN KEY (`Customer_claim_number`)
    REFERENCES `roofing`.`Customer` (`claim_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roof_Sales Representative1`
    FOREIGN KEY (`Sales Representative_sales_rep_id`)
    REFERENCES `roofing`.`Sales Representative` (`sales_rep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roofing`.`Sales Representative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roofing`.`Sales Representative` (
  `sales_rep_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `notes` VARCHAR(45) NOT NULL,
  `follow_up_email` VARCHAR(45) NOT NULL,
  `Customer_claim_number` INT NOT NULL,
  PRIMARY KEY (`sales_rep_id`),
  INDEX `fk_Sales Representative_Customer1_idx` (`Customer_claim_number` ASC) VISIBLE,
  CONSTRAINT `fk_Sales Representative_Customer1`
    FOREIGN KEY (`Customer_claim_number`)
    REFERENCES `roofing`.`Customer` (`claim_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
